# Generated by Django 3.2.15 on 2022-09-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsubject', '0002_auto_20220906_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsubject.subject'),
        ),
    ]
