# Generated by Django 4.1 on 2022-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsubject', '0007_alter_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
