# Generated by Django 4.1 on 2022-09-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsubject', '0008_enrollment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsubject.subject'),
        ),
    ]
