# Generated by Django 4.1 on 2022-09-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsubject', '0009_alter_enrollment_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='username',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsubject.subject', to_field='code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
