# Generated by Django 4.1 on 2022-09-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsubject', '0010_remove_enrollment_username_alter_enrollment_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.IntegerField(default=0),
        ),
    ]
