# Generated by Django 3.2.15 on 2022-09-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsubject', '0014_alter_enrollment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
