# Generated by Django 3.2.15 on 2022-09-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsubject', '0016_auto_20220920_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
